### PR TITLE
[NO-CI] Fix version issue

### PR DESCRIPTION
**Pull request by esezen**

### CODE REVIEW

**Review by deomsj — APPROVED** [review]
👏🏻 Nice work, @esezen 👏🏻

thank you for the quick fix!

**Review by deomsj — APPROVED** [review]
👏🏻 Nice work, @esezen 👏🏻

thank you for the quick fix!

**Review by Mudaafi — APPROVED** [review]
Tried on a local sandbox w/ the bundled version and it works as expected. I wonder if we have this problem in os-ui-ac as well 🤔

**Comment by sblaurock** [comment]
Would it be easier to just pull the version directly from package.json? Do we need a separate file to export the version number?

**Pull request merged**
