### PR TITLE
[CSL 2734] Handle Non-Json responses

### PR DESCRIPTION
**Pull request by VincentGalloro**
Handle non-json responses from server. If the server responds with plaintext we want to return an error indicating that the server responded with plaintext. The current error just says "invalid JSON ..." which doesn't make it obvious to the user that the underlying error came from a bad server response

### CODE REVIEW

**Comment by VincentGalloro** [comment]
The failed test is likely due to the new ASA bundled tests. Don't think it's related to this PR

**Review by stanlp1 — APPROVED** [review]
LGTM from what I can tell everything works properly.

**Review by esezen — CHANGES_REQUESTED** [review]
We have a failing test in the bundled version tests `npm run test:bundled`. It looks like this PR is adding `regeneratorRuntime` to the global window object. This is okay if it's intentional. Let's figure out if it is and if it's expected, we can update the test

**Comment by jjl014** [comment]
@esezen @VincentGalloro I updated the util function `converResponseToJson` to use Promises instead of async/await. Seems to resolve the issue around `regneratorRuntime` and passes all tests. 👍

**Review by stanlp1 — APPROVED** [review]
LGTM.

**Review by esezen — APPROVED** [review]

**Pull request merged**
