### PR TITLE
[CH 12097] Add support for setting client options

### PR DESCRIPTION
**Pull request by jjl014**
#### Updates:
* Add `setClientOptions` to constructorio module
* Add tests

### CODE REVIEW

**Review by rubikzube — CHANGES_REQUESTED** [review]
Sad tromobone on options setting

**Comment by jjl014** [comment]
Updated logic, all tests pass.

**Comment by jjl014** [comment]
Updated logic, all tests pass.

**Review by rubikzube — APPROVED** [review]
Works for me. Nice job

**Pull request merged**
