### PR TITLE
Add VariationsMap type

### PR DESCRIPTION
**Pull request by mocca102**

### CODE REVIEW

**Review by esezen — DISMISSED** [review]
LGTM!

**Review by esezen — CHANGES_REQUESTED** [review]
Can we update this in autocomplete and recommendations as well? Also can we update the type tests?

**Comment by mocca102** [comment]
> Can we update this in autocomplete and recommendations as well? Also can we update the type tests?

@esezen  Added. There are no tests for parameters. Maybe something to work on in the future

**Review by esezen — APPROVED** [review]
LGTM!

**Pull request merged**
