### PR TITLE
Remove 'http-server' in favor of 'serve'.

### PR DESCRIPTION
**Pull request by sblaurock**
Alleviates a security concern with dev dependency: 'http-server'.

### CODE REVIEW

**Review by jjl014 — APPROVED** [review]
lgtm! 👍

**Review by deomsj — APPROVED** [review]
nice

**Review by rubikzube — CHANGES_REQUESTED** [review]
I can haz on port 8080 or 8081?

**Comment by sblaurock** [comment]
> I can haz on port 8080 or 8081?

Sure can!

**Pull request merged**
